export const elementsData = [
  // --- ROW 1 (Top Red) ---
  { number: 5, symbol: "B", name: "Boron", type: "red", x: 13, y: 1 },
  { number: 6, symbol: "C", name: "Carbon", type: "red", x: 14, y: 1 },
  { number: 7, symbol: "N", name: "Nitrogen", type: "red", x: 15, y: 1 },
  { number: 8, symbol: "O", name: "Oxygen", type: "red", x: 16, y: 1 },

  // --- ROW 2 (Yellow & Red) ---
  { number: 13, symbol: "Al", name: "Aluminium", type: "yellow", x: 13, y: 2 },
  { number: 14, symbol: "Si", name: "Silicon", type: "yellow", x: 14, y: 2 },
  { number: 15, symbol: "P", name: "Phosphorus", type: "red", x: 15, y: 2 },
  { number: 16, symbol: "S", name: "Sulfur", type: "red", x: 16, y: 2 },

  // --- ROW 3 (Main Green & Yellow/Red) ---
  { number: 21, symbol: "Sc", name: "Scandium", type: "green", x: 3, y: 4 },
  { number: 22, symbol: "Ti", name: "Titanium", type: "green", x: 4, y: 4 },
  { number: 23, symbol: "V", name: "Vanadium", type: "green", x: 5, y: 4 },
  { number: 24, symbol: "Cr", name: "Chromium", type: "green", x: 6, y: 4 },
  { number: 25, symbol: "Mn", name: "Manganese", type: "green", x: 7, y: 4 },
  { number: 26, symbol: "Fe", name: "Iron", type: "green", x: 8, y: 4 },
  { number: 27, symbol: "Co", name: "Cobalt", type: "green", x: 9, y: 4 },
  { number: 28, symbol: "Ni", name: "Nickel", type: "green", x: 10, y: 4 },
  { number: 29, symbol: "Cu", name: "Copper", type: "green", x: 11, y: 4 },
  { number: 30, symbol: "Zn", name: "Zinc", type: "green", x: 12, y: 4 },
  { number: 31, symbol: "Ga", name: "Gallium", type: "yellow", x: 13, y: 4 },
  { number: 32, symbol: "Ge", name: "Germanium", type: "yellow", x: 14, y: 4 },
  { number: 33, symbol: "As", name: "Arsenic", type: "yellow", x: 15, y: 4 },
  { number: 34, symbol: "Se", name: "Selenium", type: "red", x: 16, y: 4 },

  // --- ROW 4 (Green & Yellow) ---
  { number: 39, symbol: "Y", name: "Yttrium", type: "green", x: 3, y: 5 },
  { number: 40, symbol: "Zr", name: "Zirconium", type: "green", x: 4, y: 5 },
  { number: 41, symbol: "Nb", name: "Niobium", type: "green", x: 5, y: 5 },
  { number: 42, symbol: "Mo", name: "Molybdenum", type: "green", x: 6, y: 5 },
  { number: 43, symbol: "Tc", name: "Technetium", type: "green", x: 7, y: 5 },
  { number: 44, symbol: "Ru", name: "Ruthenium", type: "green", x: 8, y: 5 },
  { number: 45, symbol: "Rh", name: "Rhodium", type: "green", x: 9, y: 5 },
  { number: 46, symbol: "Pd", name: "Palladium", type: "green", x: 10, y: 5 },
  { number: 47, symbol: "Ag", name: "Silver", type: "green", x: 11, y: 5 },
  { number: 48, symbol: "Cd", name: "Cadmium", type: "green", x: 12, y: 5 },
  { number: 49, symbol: "In", name: "Indium", type: "yellow", x: 13, y: 5 },
  { number: 50, symbol: "Sn", name: "Tin", type: "yellow", x: 14, y: 5 },
  { number: 51, symbol: "Sb", name: "Antimony", type: "yellow", x: 15, y: 5 },
  { number: 52, symbol: "Te", name: "Tellurium", type: "yellow", x: 16, y: 5 },

  // --- ROW 5 (Green & Yellow) ---
  { number: 72, symbol: "Hf", name: "Hafnium", type: "green", x: 4, y: 6 },
  { number: 73, symbol: "Ta", name: "Tantalum", type: "green", x: 5, y: 6 },
  { number: 74, symbol: "W", name: "Tungsten", type: "green", x: 6, y: 6 },
  { number: 75, symbol: "Re", name: "Rhenium", type: "green", x: 7, y: 6 },
  { number: 76, symbol: "Os", name: "Osmium", type: "green", x: 8, y: 6 },
  { number: 77, symbol: "Ir", name: "Iridium", type: "green", x: 9, y: 6 },
  { number: 78, symbol: "Pt", name: "Platinum", type: "green", x: 10, y: 6 },
  { number: 79, symbol: "Au", name: "Gold", type: "green", x: 11, y: 6 },
  { number: 80, symbol: "Hg", name: "Mercury", type: "green", x: 12, y: 6 },
  { number: 81, symbol: "Tl", name: "Thallium", type: "yellow", x: 13, y: 6 },
  { number: 82, symbol: "Pb", name: "Lead", type: "yellow", x: 14, y: 6 },
  { number: 83, symbol: "Bi", name: "Bismuth", type: "yellow", x: 15, y: 6 },
  { number: 84, symbol: "Po", name: "Polonium", type: "yellow", x: 16, y: 6 },

  // --- ROW 6 (Cyan & Yellow) ---
  { number: 104, symbol: "Rf", name: "Rutherfordium", type: "cyan", x: 4, y: 7 },
  { number: 105, symbol: "Db", name: "Dubnium", type: "cyan", x: 5, y: 7 },
  { number: 106, symbol: "Sg", name: "Seaborgium", type: "cyan", x: 6, y: 7 },
  { number: 107, symbol: "Bh", name: "Bohrium", type: "cyan", x: 7, y: 7 },
  { number: 108, symbol: "Hs", name: "Hassium", type: "cyan", x: 8, y: 7 },
  { number: 109, symbol: "Mt", name: "Meitnerium", type: "cyan", x: 9, y: 7 },
  { number: 110, symbol: "Ds", name: "Darmstadtium", type: "cyan", x: 10, y: 7 },
  { number: 111, symbol: "Rg", name: "Roentgenium", type: "cyan", x: 11, y: 7 },
  { number: 112, symbol: "Cn", name: "Copernicium", type: "cyan", x: 12, y: 7 },
  { number: 113, symbol: "Nh", name: "Nihonium", type: "cyan", x: 13, y: 7 },
  { number: 114, symbol: "Fl", name: "Flerovium", type: "cyan", x: 14, y: 7 },
  { number: 115, symbol: "Mc", name: "Moscovium", type: "cyan", x: 15, y: 7 },
  { number: 116, symbol: "Lv", name: "Livermorium", type: "cyan", x: 16, y: 7 },

  // --- LANTHANIDES (Cyan bottom row 1) ---
  { number: 57, symbol: "La", name: "Lanthanum", type: "cyan", x: 3, y: 9 },
  { number: 58, symbol: "Ce", name: "Cerium", type: "cyan", x: 4, y: 9 },
  { number: 59, symbol: "Pr", name: "Praseodymium", type: "cyan", x: 5, y: 9 },
  { number: 60, symbol: "Nd", name: "Neodymium", type: "cyan", x: 6, y: 9 },
  { number: 61, symbol: "Pm", name: "Promethium", type: "cyan", x: 7, y: 9 },
  { number: 62, symbol: "Sm", name: "Samarium", type: "cyan", x: 8, y: 9 },
  { number: 63, symbol: "Eu", name: "Europium", type: "cyan", x: 9, y: 9 },
  { number: 64, symbol: "Gd", name: "Gadolinium", type: "cyan", x: 10, y: 9 },
  { number: 65, symbol: "Tb", name: "Terbium", type: "cyan", x: 11, y: 9 },
  { number: 66, symbol: "Dy", name: "Dysprosium", type: "cyan", x: 12, y: 9 },
  { number: 67, symbol: "Ho", name: "Holmium", type: "cyan", x: 13, y: 9 },
  { number: 68, symbol: "Er", name: "Erbium", type: "cyan", x: 14, y: 9 },
  { number: 69, symbol: "Tm", name: "Thulium", type: "cyan", x: 15, y: 9 },
  { number: 70, symbol: "Yb", name: "Ytterbium", type: "cyan", x: 16, y: 9 },

  // --- ACTINIDES (Cyan bottom row 2) ---
  { number: 89, symbol: "Ac", name: "Actinium", type: "cyan", x: 3, y: 10 },
  { number: 90, symbol: "Th", name: "Thorium", type: "cyan", x: 4, y: 10 },
  { number: 91, symbol: "Pa", name: "Protactinium", type: "cyan", x: 5, y: 10 },
  { number: 92, symbol: "U", name: "Uranium", type: "cyan", x: 6, y: 10 },
  { number: 93, symbol: "Np", name: "Neptunium", type: "cyan", x: 7, y: 10 },
  { number: 94, symbol: "Pu", name: "Plutonium", type: "cyan", x: 8, y: 10 },
  { number: 95, symbol: "Am", name: "Americium", type: "cyan", x: 9, y: 10 },
  { number: 96, symbol: "Cm", name: "Curium", type: "cyan", x: 10, y: 10 },
  { number: 97, symbol: "Bk", name: "Berkelium", type: "cyan", x: 11, y: 10 },
  { number: 98, symbol: "Cf", name: "Californium", type: "cyan", x: 12, y: 10 },
  { number: 99, symbol: "Es", name: "Einsteinium", type: "cyan", x: 13, y: 10 },
  { number: 100, symbol: "Fm", name: "Fermium", type: "cyan", x: 14, y: 10 },
  { number: 101, symbol: "Md", name: "Mendelevium", type: "cyan", x: 15, y: 10 },
  { number: 102, symbol: "No", name: "Nobelium", type: "cyan", x: 16, y: 10 },
];